### ISSUE TITLE
HAML Support

### ISSUE THREAD

**Issue by allenmackley** [bitmovin/bitmovin-player-rails#1]
When I run "rails generate bitmovin_player" it fails because it can't find application.html.erb. This is because my application file is titled application.html.haml. I tried creating an empty application.html.erb file and was able to run the generator, however, it didn't install the helper and then I get an error: "undefined method `bitmovin_player'"

insert  app/views/layouts/application.html.erb
/Users/AcousticAce/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/actions/inject_into_file.rb:95:in `binread': No such file or directory @ rb_sysopen - /Users/AcousticAce/Sites/mackleystudios/app/views/layouts/application.html.erb (Errno::ENOENT)

**Comment by Tigraine** [comment]
Hi @allenmackley thanks for pointing out the missing HAML support.
I just released a new version to Rubygems that hopefully fixes the HAML support for you. Please let me know if it works or you need anything else.

Caveat: 
You might have to tweak the `application.html.haml` file a bit due since inserting the helper at the right indentation level is tricky, but that's also noted in the generator output.

Also I made the installer a bit more robust: It will try to install into `application.html.erb` or `.haml` but not just blow up if there is neither present so people should at least get the helpers even though the generator could not do all of it's magic.

Hope this helps! I'm closing this, if there is anything with HAML support we can still improve please either open a new issue or we'll reopen this.

Happy Holidays,
greetings Daniel

**Comment by allenmackley** [comment]
HI Tigraine, thanks very much, it works now!

One question I have is about the HTML div element that's added to the page with a random id, for example "<div id='bitmovin-08d5a'>". Is there a way to set my own custom id?

**Comment by Tigraine** [comment]
Hi @allenmackley - yes of course this can be set through the `container: 'foo'` option. 
If it's not set it gets auto-generated. But of course you can provide your own.

`<%= bitmovin_player(container: 'my-container-id' ... `

The code in question is here: https://github.com/bitmovin/bitmovin-player-rails/blob/master/lib/bitmovin/player/rails/helper.rb#L8

**Comment by allenmackley** [comment]
Great, thanks so much! This is a really great gem and I love all of the new improvements to the version 7 player.
